from typing import Protocol

from app.domain.entities import (
    Product,
    ProductPincode,
    StockHistory,
    User,
    UserDefaultPincode,
    UserProductTracking,
)


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...
    async def upsert(self, user: User) -> User: ...
    async def get(self, user_id: int) -> User | None: ...
    async def get_by_telegram_id(self, telegram_user_id: int) -> User | None: ...


class ProductRepository(Protocol):
    async def create(self, product: Product) -> Product: ...
    async def get(self, product_id: int) -> Product | None: ...
    async def get_by_marketplace_product_id(
        self, marketplace: str, product_id: str
    ) -> Product | None: ...
    async def update(self, product: Product) -> Product: ...
    async def delete(self, product_id: int) -> None: ...
    async def list_active_tracked(self) -> list[Product]: ...


class ProductPincodeRepository(Protocol):
    async def add(self, pincode: ProductPincode) -> ProductPincode: ...
    async def list_for_product(self, product_id: int) -> list[ProductPincode]: ...
    async def remove(self, product_id: int, pincode: str) -> None: ...


class UserDefaultPincodeRepository(Protocol):
    async def list_for_user(self, user_id: int) -> list[UserDefaultPincode]: ...
    async def replace_for_user(
        self, user_id: int, pincodes: list[str]
    ) -> list[UserDefaultPincode]: ...


class UserProductTrackingRepository(Protocol):
    async def create(self, tracking: UserProductTracking) -> UserProductTracking: ...
    async def get(self, user_id: int, product_id: int) -> UserProductTracking | None: ...
    async def list_for_user(self, user_id: int) -> list[UserProductTracking]: ...
    async def list_for_product(self, product_id: int) -> list[UserProductTracking]: ...
    async def update_notification_state(
        self, tracking: UserProductTracking
    ) -> UserProductTracking: ...
    async def delete(self, user_id: int, product_id: int) -> None: ...


class StockHistoryRepository(Protocol):
    async def record(self, stock_history: StockHistory) -> StockHistory: ...
    async def list_for_product(self, product_id: int) -> list[StockHistory]: ...
